app = "chessome-api"
primary_region = "iad"

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  timeout = "2s"
  method = "GET"
  path = "/v1/health"

[processes]
  app = "node apps/api/dist/main.js"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1
